services:
  dailydisplay:
    build: .
    # For pre-built images from GitHub Container Registry:
    # image: ghcr.io/max.schaefer/dailydisplay:latest
    container_name: dailydisplay
    restart: unless-stopped
    ports:
      - "7777:7777"
    environment:
      # Multi-user configuration as JSON
      CONFIG: |
        {
          "user1_hash": {
            "timezone": "America/New_York",
            "weather_location": "New York, NY",
            "caldav_urls": "https://user:pass@calendar.example.com/cal.ics",
            "caldav_filter_names": "personal,work"
          },
          "user2_hash": {
            "timezone": "Europe/London", 
            "weather_location": "London, UK",
            "caldav_urls": "https://user:pass@calendar.provider.com/calendar.ics,https://user:pass@work.calendar.com/work.ics",
            "caldav_filter_names": "home"
          }
        }
    # Optional: Mount config from file instead of environment variable
    # volumes:
    #   - ./config.json:/app/config.json:ro
    # environment:
    #   CONFIG_FILE: /app/config.json
    
    # Optional: Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Reverse proxy with SSL termination
  # nginx:
  #   image: nginx:alpine
  #   container_name: dailydisplay-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - dailydisplay

# Optional: Custom network for isolation
# networks:
#   dailydisplay:
#     driver: bridge